import asyncio
import json
import logging
import time
from datetime import datetime, timezone
import psycopg2

import paho.mqtt.client as mqtt

# Configuration
BROKER = "localhost"
PORT = 1883
DB_URI = "postgresql://uns_admin:uns_dev_password@localhost:5432/uns_timeseries"
API_URL = "http://localhost:8000/api/v1"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("e2e_test")

def publish(client, topic, payload):
    logger.info(f"Publishing to {topic}: {payload}")
    client.publish(topic, json.dumps(payload), qos=1)
    time.sleep(2)  # Give Data Engine & Backend time to process


def verify_db_telemetry(run_id, lot_id):
    logger.info("Verifying database for injected context...")
    conn = psycopg2.connect(DB_URI)
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT time, value, run_id, lot_id 
            FROM ts_telemetry 
            ORDER BY time DESC LIMIT 1
            """
        )
        row = cur.fetchone()
        if row:
            logger.info(f"DB Record: value={row[1]}, run_id={row[2]}, lot_id={row[3]}")
            assert row[2] == run_id, f"Expected run_id={run_id}, got {row[2]}"
            assert row[3] == lot_id, f"Expected lot_id={lot_id}, got {row[3]}"
            logger.info("✅ Database verification PASSED: Context injected correctly!")
        else:
            logger.error("❌ No telemetry records found!")
    finally:
        conn.close()

def main():
    logger.info("Starting E2E Test for Production Context Enrichment (ADR-003 Phase 2.5)")
    
    # Setup MQTT Client
    client = mqtt.Client(client_id="e2e_test_context")
    client.connect(BROKER, PORT)
    client.loop_start()

    eq_path = "TaiwanPrecision/Taoyuan/SMT_Line_1/SMT-Mounter-01"
    lot_topic = f"{eq_path}/Event"
    tel_topic = f"{eq_path}/Telemetry"
    
    test_lot = "LOT-TEST-999"

    # Step 1: Send LOT_START
    payload_start = {
        "event_code": "LOT_START",
        "lot_id": test_lot,
        "step_id": "STEP-01",
        "recipe_id": "RECIPE-A"
    }
    publish(client, lot_topic, payload_start)

    # Note: we don't know the exact run_id generated by the backend, but we can verify lot_id directly.
    # We will assume run_id is not null if lot_id is present.

    # Step 2: Send Telemetry to the exact topic mapped in DB
    payload_tel = {
        "temperature": 45.5,
        "pressure": 10.2,
        "recipe_name": "RECIPE-A"
    }
    publish(client, tel_topic, payload_tel)

    # Step 3: Send LOT_END
    payload_end = {
        "event_code": "LOT_END",
        "lot_id": test_lot
    }
    publish(client, lot_topic, payload_end)
    
    # Step 4: Verify
    logger.info("Checking TimescaleDB...")
    conn = psycopg2.connect(DB_URI)
    try:
        cur = conn.cursor()
        # Find the tag_id for the telemetry topic
        cur.execute("SELECT tag_id FROM tag_source_mapping WHERE mqtt_topic = %s", (f"{tel_topic}::temperature",))
        tag_row = cur.fetchone()
        if tag_row:
            tag_id = tag_row[0]
            cur.execute(
                """
                SELECT time, value, run_id, lot_id 
                FROM ts_telemetry 
                WHERE tag_id = %s
                ORDER BY time DESC LIMIT 1
                """, (tag_id,)
            )
            row = cur.fetchone()
            if row:
                logger.info(f"DB Record: value={row[1]}, run_id={row[2]}, lot_id={row[3]}")
                if row[3] == test_lot and row[2] is not None:
                     logger.info("✅ Core Requirement Met: lot_id and run_id injected into telemetry.")
                else:
                     logger.error(f"❌ Verification Failed. Expected lot_id={test_lot}, got {row[3]}. run_id={row[2]}")
            else:
                logger.error("❌ No telemetry records found!")
        else:
             logger.error(f"❌ No Tag found for {tel_topic}")
    finally:
        conn.close()

    client.loop_stop()
    client.disconnect()
    logger.info("Test finished.")

if __name__ == "__main__":
    main()
